name: Cypress Tests

on:
  push:
    branches:
      - develop

jobs:
    Cypress-run:
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout
          uses: actions/checkout@v4
        - name: start app
          run: npm run dev
        - name: Cypress run
          uses: cypress-io/github-action@v6
          with:
            command: npm run test
        - name: Uploading artifacts
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: cypress-execution-report
            if-no-files-found: error
            path: cypress/results/mochawesome
            retention-days: 30



      
